const vid=[
     {
         src:"https://www.youtube.com/embed/tgbNymZ7vqY",
         title:"Hakuna"
     },
     {
        src:"https://www.youtube.com/embed/tgbNymZ7vqY",
        title:"Hakuna"
    },
    {
        src:"https://www.youtube.com/embed/tgbNymZ7vqY",
        title:"Hakuna"
    },
    {
        src:"https://www.youtube.com/embed/tgbNymZ7vqY",
        title:"Hakuna"
    },
    {
        src:"https://www.youtube.com/embed/tgbNymZ7vqY",
        title:"Hakuna"
    },
    {
        src:"https://www.youtube.com/embed/tgbNymZ7vqY",
        title:"Hakuna"
    },
    {
        src:"https://www.youtube.com/embed/tgbNymZ7vqY",
        title:"Hakuna"
    },
    {
        src:"https://www.youtube.com/embed/tgbNymZ7vqY",
        title:"Hakuna"
    },
    {
        src:"https://www.youtube.com/embed/tgbNymZ7vqY",
        title:"Hakuna"
    },
    {
        src:"https://www.youtube.com/embed/tgbNymZ7vqY",
        title:"Hakuna"
    },
    {
        src:"https://www.youtube.com/embed/tgbNymZ7vqY",
        title:"Hakuna"
    },
    {
        src:"https://www.youtube.com/embed/tgbNymZ7vqY",
        title:"Hakuna"
    },
];

export default vid;